version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.21
    - 6.2.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: next
    versions:
    - 10.0.9
  - dependency-name: styled-icons
    versions:
    - 10.31.0
